const INPUT = 'INPUT';
const TEXTAREA = 'TEXTAREA';
const RADIO = 'RADIO';
const SWITCH = 'SWITCH';
const CHECKBOX = 'CHECKBOX';
const SELECT = 'SELECT';
const UPLOAD = 'UPLOAD';
const DATE = 'DATE';
const DATETIME = 'DATETIME';
const DATERANGE = 'DATERANGE';
const DATETIMERANGE = 'DATETIMERANGE';
const CUSTOM_COMPONENT = 'CUSTOM_COMPONENT';
const INPUTNUMBER = 'INPUTNUMBER';

export {
  INPUT,
  TEXTAREA,
  RADIO,
  SWITCH,
  CHECKBOX,
  SELECT,
  UPLOAD,
  DATE,
  DATETIME,
  DATERANGE,
  DATETIMERANGE,
  CUSTOM_COMPONENT,
  INPUTNUMBER
};
